version: "3.7"

networks:
  rijk.network:
    driver: bridge
services:
  apache-php:
    build: ./
    restart: always
    container_name: rijk
    networks:
      - rijk.network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
    environment:
      DOMAINS: "www.rijk.com.br"
      EMAIL: "alex@rijk.com"
      PAGESPEED: "true"
      LIBMOD: "re2c"
      APAMOD: "cache,rewrite,ssl,headers"
      APDMOD: "autoindex"
      PHPMOD: "bcmath,bz2,intl,gd,mbstring,mysql,zip"
      PEAMOD: "xdiff"
    volumes:
      - ./app:/var/www/html
      - ./docker/webserver/app.conf:/etc/apache2/sites-available/000-default.conf

  postgres:
    container_name: rijk.postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    networks:
      - rijk.network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=02W@9889forev
      - POSTGRES_DB=aut_rijk
